#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start eww daemon
eww daemon &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &> /dev/null &
  # picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

# Set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

eww open bar 
